# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cimex/Projects/Computer_Graphics/no_nonsense_engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cimex/Projects/Computer_Graphics/no_nonsense_engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cimex/Projects/Computer_Graphics/no_nonsense_engine/CMakeFiles /home/cimex/Projects/Computer_Graphics/no_nonsense_engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cimex/Projects/Computer_Graphics/no_nonsense_engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named no_nonsense_engine

# Build rule for target.
no_nonsense_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 no_nonsense_engine
.PHONY : no_nonsense_engine

# fast build rule for target.
no_nonsense_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/build
.PHONY : no_nonsense_engine/fast

dependencies/microui/microui.o: dependencies/microui/microui.c.o
.PHONY : dependencies/microui/microui.o

# target to build an object file
dependencies/microui/microui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/dependencies/microui/microui.c.o
.PHONY : dependencies/microui/microui.c.o

dependencies/microui/microui.i: dependencies/microui/microui.c.i
.PHONY : dependencies/microui/microui.i

# target to preprocess a source file
dependencies/microui/microui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/dependencies/microui/microui.c.i
.PHONY : dependencies/microui/microui.c.i

dependencies/microui/microui.s: dependencies/microui/microui.c.s
.PHONY : dependencies/microui/microui.s

# target to generate assembly for a file
dependencies/microui/microui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/dependencies/microui/microui.c.s
.PHONY : dependencies/microui/microui.c.s

src/image_view.o: src/image_view.c.o
.PHONY : src/image_view.o

# target to build an object file
src/image_view.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/image_view.c.o
.PHONY : src/image_view.c.o

src/image_view.i: src/image_view.c.i
.PHONY : src/image_view.i

# target to preprocess a source file
src/image_view.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/image_view.c.i
.PHONY : src/image_view.c.i

src/image_view.s: src/image_view.c.s
.PHONY : src/image_view.s

# target to generate assembly for a file
src/image_view.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/image_view.c.s
.PHONY : src/image_view.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/main.c.s
.PHONY : src/main.c.s

src/model.o: src/model.c.o
.PHONY : src/model.o

# target to build an object file
src/model.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/model.c.o
.PHONY : src/model.c.o

src/model.i: src/model.c.i
.PHONY : src/model.i

# target to preprocess a source file
src/model.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/model.c.i
.PHONY : src/model.c.i

src/model.s: src/model.c.s
.PHONY : src/model.s

# target to generate assembly for a file
src/model.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/model.c.s
.PHONY : src/model.c.s

src/render.o: src/render.c.o
.PHONY : src/render.o

# target to build an object file
src/render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/render.c.o
.PHONY : src/render.c.o

src/render.i: src/render.c.i
.PHONY : src/render.i

# target to preprocess a source file
src/render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/render.c.i
.PHONY : src/render.c.i

src/render.s: src/render.c.s
.PHONY : src/render.s

# target to generate assembly for a file
src/render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/render.c.s
.PHONY : src/render.c.s

src/tga_image.o: src/tga_image.c.o
.PHONY : src/tga_image.o

# target to build an object file
src/tga_image.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/tga_image.c.o
.PHONY : src/tga_image.c.o

src/tga_image.i: src/tga_image.c.i
.PHONY : src/tga_image.i

# target to preprocess a source file
src/tga_image.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/tga_image.c.i
.PHONY : src/tga_image.c.i

src/tga_image.s: src/tga_image.c.s
.PHONY : src/tga_image.s

# target to generate assembly for a file
src/tga_image.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/tga_image.c.s
.PHONY : src/tga_image.c.s

src/transformation.o: src/transformation.c.o
.PHONY : src/transformation.o

# target to build an object file
src/transformation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/transformation.c.o
.PHONY : src/transformation.c.o

src/transformation.i: src/transformation.c.i
.PHONY : src/transformation.i

# target to preprocess a source file
src/transformation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/transformation.c.i
.PHONY : src/transformation.c.i

src/transformation.s: src/transformation.c.s
.PHONY : src/transformation.s

# target to generate assembly for a file
src/transformation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/transformation.c.s
.PHONY : src/transformation.c.s

src/type.o: src/type.c.o
.PHONY : src/type.o

# target to build an object file
src/type.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/type.c.o
.PHONY : src/type.c.o

src/type.i: src/type.c.i
.PHONY : src/type.i

# target to preprocess a source file
src/type.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/type.c.i
.PHONY : src/type.c.i

src/type.s: src/type.c.s
.PHONY : src/type.s

# target to generate assembly for a file
src/type.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/type.c.s
.PHONY : src/type.c.s

src/util/util.o: src/util/util.c.o
.PHONY : src/util/util.o

# target to build an object file
src/util/util.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/util/util.c.o
.PHONY : src/util/util.c.o

src/util/util.i: src/util/util.c.i
.PHONY : src/util/util.i

# target to preprocess a source file
src/util/util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/util/util.c.i
.PHONY : src/util/util.c.i

src/util/util.s: src/util/util.c.s
.PHONY : src/util/util.s

# target to generate assembly for a file
src/util/util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/util/util.c.s
.PHONY : src/util/util.c.s

src/vector_math.o: src/vector_math.c.o
.PHONY : src/vector_math.o

# target to build an object file
src/vector_math.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/vector_math.c.o
.PHONY : src/vector_math.c.o

src/vector_math.i: src/vector_math.c.i
.PHONY : src/vector_math.i

# target to preprocess a source file
src/vector_math.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/vector_math.c.i
.PHONY : src/vector_math.c.i

src/vector_math.s: src/vector_math.c.s
.PHONY : src/vector_math.s

# target to generate assembly for a file
src/vector_math.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/no_nonsense_engine.dir/build.make CMakeFiles/no_nonsense_engine.dir/src/vector_math.c.s
.PHONY : src/vector_math.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... no_nonsense_engine"
	@echo "... dependencies/microui/microui.o"
	@echo "... dependencies/microui/microui.i"
	@echo "... dependencies/microui/microui.s"
	@echo "... src/image_view.o"
	@echo "... src/image_view.i"
	@echo "... src/image_view.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/render.o"
	@echo "... src/render.i"
	@echo "... src/render.s"
	@echo "... src/tga_image.o"
	@echo "... src/tga_image.i"
	@echo "... src/tga_image.s"
	@echo "... src/transformation.o"
	@echo "... src/transformation.i"
	@echo "... src/transformation.s"
	@echo "... src/type.o"
	@echo "... src/type.i"
	@echo "... src/type.s"
	@echo "... src/util/util.o"
	@echo "... src/util/util.i"
	@echo "... src/util/util.s"
	@echo "... src/vector_math.o"
	@echo "... src/vector_math.i"
	@echo "... src/vector_math.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

